### PR TITLE
SmolStation Update

### PR DESCRIPTION
**Pull request by CipherSnagger**
# About The Pull Request

Makes SmolStation usable for 20 pop or less. Don't forget to set a player cap for this horrible map in configs!

## Why It's Good For The Game

It's not.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added Brig Phys spawn and locker to brig medbay
add: Added Psychologist spawn and locker to medbay
add: Added Blueshield spawn and locker to AI sat shuttle room
add: Added Bridge Officer spawn and lockers to bridge
tweak: Replaced an AI sat door with bridge door
/:cl:

### CODE REVIEW

**Comment by kiwilover8** [comment]
If you're going to continue 1:1 copying my updates for Vice, including the changelog, at least credit me.

**Comment by kiwilover8** [comment]
You're also obligated to give credit under the licenses the station code runs off of.

**Comment by CipherSnagger** [comment]
> If you're going to continue 1:1 copying my updates for Vice, including the changelog, at least credit me.

Credit: me

**Comment by NullDagaf** [comment]
> You're also obligated to give credit under the licenses the station code runs off of.

Sadly, no.

**Pull request merged**
